schema_version: 1
name: jboss.container.eap.prometheus.jmx-exporter-config
version: '7.2'
description: Provides Prometheus JMX Exporter configuration for use with EAP 7.2

execute:
- script: configure.sh
